name: Build and Test on Linux and Mac OS

on:
  pull_request:
    branches:
      - '**'

jobs:

  Linux:

    runs-on: ubuntu-22.04

    steps:
    - name: Install Packages
      run: sudo apt-get install make

    - uses: actions/checkout@v1

    - name: run CI script
      run: ./tools/ci.sh

  Linux-20-04:

    runs-on: ubuntu-20.04

    steps:
    - name: Install Packages
      run: sudo apt-get install make

    - uses: actions/checkout@v1

    - name: run CI script
      run: ./tools/ci.sh

  Linux-18-04:

    runs-on: ubuntu-18.04

    steps:
    - name: Install Packages
      run: sudo apt-get install make

    - uses: actions/checkout@v1

    - name: run CI script
      run: ./tools/ci.sh

  MacOS:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1

    - name: run CI script
      run: ./tools/ci.sh

